[package]
name = "soapy"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "Structure-of-arrays derive macro"
homepage = "https://github.com/tim-harding/soapy"
repository = "https://github.com/tim-harding/soapy"
readme = "README.md"

[workspace]
members = ["soapy-derive", "soapy-shared"]

[dependencies]
soapy-derive = { path = "soapy-derive", version = "0.2.0" }
soapy-shared = { path = "soapy-shared", version = "0.2.0" }
