[package]
name = "soapy"
version = "0.2.6"
edition = "2021"
license = "MIT"
description = "Structure-of-arrays derive macro"
homepage = "https://github.com/tim-harding/soapy"
repository = "https://github.com/tim-harding/soapy"
readme = "README.md"

[profile.bench]
# For profiling
debug = true 

[workspace]
members = ["soapy-derive", "soapy-testing"]

[dependencies]
soapy-derive = { path = "soapy-derive", version = "0.2.6" }
