[package]
name = "soa-rs-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
soa-rs = { version = "0.3.0", path = ".." }
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "benchmark"
harness = false
